name: nx_di
description: >-
  A high-performance dependency injection library for Dart and Flutter. 
  Features multi-profile support and serves as a drop-in replacement for 
  get_it with enhanced capabilities.
version: 0.7.1
homepage: https://github.com/salah-alhajj/nx_di
repository: https://github.com/salah-alhajj/nx_di
issue_tracker: https://github.com/salah-alhajj/nx_di/issues
documentation: https://pub.dev/documentation/nx_di
license: MIT
topics:
  - dependency-injection
  - service-locator  
  - architecture
  - profiles
  - get-it

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  args: ^2.7.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.0
  mockito: ^5.4.2
  build_runner: ^2.4.7
  coverage: ^1.8.0

executables:
  nx-migrate: bin/migrate_from_get_it
